### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/docker-training#1]
As a trainee I would like the provided examples to be supported by my operating system of choice (Windows) :P

**Acceptance Criteria**
- [x] provided examples should be executable under a windows environment, alternatively, an adapted syntax for windows should be provided. 
- [ ] if something simply isn't possible to work with windows (I wouldn't be surprised) it should be stated, or VMs running Linux could be provided

**Comment by AdrianFarmadin** [comment]
@fhochleitner Works `docker-compose.yml` if you first set `$Env:COMPOSE_CONVERT_WINDOWS_PATHS=1` in windows shell ?

**Comment by AdrianFarmadin** [comment]
Readme for powershell updated in b7ee4be

**Comment by fhochleitner** [comment]
added additional information for clarity to the updated readme file

**Comment by cchet** [comment]
Maybe add doc about accessing docker via windows WSL, by
- setting DOCKER_HOST=tcp://127.0.0.1:<port> (not localhost !!!)
- enabling 'Expose API ...' in Docker for Windows,
- and installing docker and docker-compose in the WSL.

Docker-compose should work as well.

**Comment by cchet** [comment]
I think this issue is done, don't you think ?

**Comment by cchet** [comment]
I close this issue, because already done
